### PR TITLE
Can now sort by price

### PR DESCRIPTION
**Pull request by nickGraham0**
Can now sort by price (price info is not supplied by Google Places API so a call to Google Details API w/ each place's id was required). 

Made Georgia Tech's Location the default location

Added Price Level info to Results List

### CODE REVIEW

**Comment by nickGraham0** [comment]
Merged with updated main branch w/ all previous PR changes. Merge is broken:

Map.js:128 Error during search: AuthenticationError: 401 Incorrect API key provided: sk-proj-********************************************************************************************************************************************************4gEA. You can find your API key at https://platform.openai.com/account/api-keys.
    at APIError.generate (error.ts:74:1)
    at OpenAI.makeStatusError (core.ts:431:1)
    at OpenAI.makeRequest (core.ts:495:1)
    at async getSynonyms (GPTRequest.js:6:1)
    at async handleSubmit (Map.js:67:1)

**Review by nerdgamer2662 — APPROVED** [review]
Looks good to merge

**Comment by nickGraham0** [comment]
note that retrieving the price data from Google Details API is slower so will be slight delay in results showing up

**Comment by ikhyunAn** [comment]
Looks good to me

**Review by jyang759 — COMMENTED** [review]
great changes, big contribution!

**Pull request merged**
