### PR TITLE
UI Edits: Added stars next to the ratings, changed colors of search and dashboard buttons, added a hover feature for certain buttons

### PR DESCRIPTION
**Pull request by jyang759**

### CODE REVIEW

**Review by ikhyunAn — DISMISSED** [review]
This might cause merge conflict.
Two solutions:
1. Justin can resolve the merge conflicts by merging the current main branch into his branch - `advanced_filtering`. After that submit a new pull request
2. After reviewing choose `rebase` option .. I'm not 100% sure if this can solve the issue

**Review by JHCuc3m — DISMISSED** [review]
Manually resolve any conflicts if there are before merging.

**Review by ikhyunAn — DISMISSED** [review]

**Review by JHCuc3m — DISMISSED** [review]

**Review by JHCuc3m — DISMISSED** [review]

**Review by JHCuc3m — DISMISSED** [review]
reapprove

**Review by nerdgamer2662 — DISMISSED** [review]
Should be good to merge

**Review by nerdgamer2662 — APPROVED** [review]
Addressed issue with automatic stale PR dismissal, this should stick now

**Review by JHCuc3m — APPROVED** [review]
Seems to work

**Review by nickGraham0 — APPROVED** [review]
Nice additions to map

**Pull request merged**
