### PR TITLE
Allow user to specify type

### PR DESCRIPTION
**Pull request by ikhyunAn**

### CODE REVIEW

**Comment by nickGraham0** [comment]
Am having trouble getting this to work. Used 'restaurants' as keywork and no result.

**Comment by ikhyunAn** [comment]
Can you try bar?

**Comment by ikhyunAn** [comment]
Right now the keyword needs to be specifically follow google API

**Comment by ikhyunAn** [comment]
https://developers.google.com/maps/documentation/javascript/supported_types
^ access this page for those keywords

**Comment by ikhyunAn** [comment]
`restaurants` don't work because it should be `restaurant`

**Comment by nickGraham0** [comment]
restaurant, bar work. Noted about supported types functionality

**Review by nickGraham0 — APPROVED** [review]
Seems to work

**Pull request merged**
