### PR TITLE
Interactive map

### PR DESCRIPTION
**Pull request by nerdgamer2662**
The map can be clicked to obtain a new lat/long, and the radius can be set (in miles). The search filters are hardcoded, but the markers are hoverable and clickable with all the information specified in the MMFs.

### CODE REVIEW

**Review by JHCuc3m — COMMENTED** [review]
¿Why files for locationsearch client/server files that implement MMF1 are deleted?

**Comment by nerdgamer2662** [comment]
@nickGraham0 It seems like you deleted MMF1 in one of your commits (the first in this PR). Was this intentional?

**Comment by nickGraham0** [comment]
@JHCuc3m MMF1 files were deleted for developmental reasons. Intention was to integrate map to MMF1 once development was completed.

**Comment by ikhyunAn** [comment]
I don't think we can merge this one. server / client application should've remained the same

**Review by ghost — APPROVED** [review]
Good work

**Pull request closed without merging**
