### PR TITLE
sort by distance and ratings

### PR DESCRIPTION
**Pull request by nickGraham0**
First Bullet point of Second part of MMF3

User can now sort the results by ratings OR distance. Price sort is implemented but requires retrieval of price info through an additional call to Google Details API (TODO at later point). Google Places API is not suitable for retrieving price level data (see notice at top of: https://developers.google.com/maps/documentation/places/web-service/details#fields) 

Console logs are included (In maputils.js) for the benifit of reviewers to ensure that ratings and distance are actually sorted.

Increased max results to 10... this is for testing. Later dev will involve a custom number for max result that the user can input.

Brought back Vjiay's (@nerdgamer2662) haversine distance function to calculate place distance from map center using each location's lat/long.

### CODE REVIEW

**Review by nerdgamer2662 — CHANGES_REQUESTED** [review]
Works, might want to make different sorts mutually exclusive?

**Comment by nickGraham0** [comment]
Will add exclusion between the sorts

**Review by nerdgamer2662 — APPROVED** [review]
Should be good to merge

**Comment by jyang759** [comment]
looks good, rereview from new account

**Pull request merged**
